# Ph√¢n t√≠ch d·ªØ li·ªáu nh√¢n vi√™n

Notebook n√†y s·ª≠ d·ª•ng module `data_processor` ƒë·ªÉ x·ª≠ l√Ω d·ªØ li·ªáu nh√¢n vi√™n t·ª´ file Excel v√† t·∫°o b√°o c√°o.

In [1]:
import sys
import os

# Th√™m ƒë∆∞·ªùng d·∫´n modules v√†o sys.path
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'modules'))

from data_processor import read_excel_file, save_to_excel, merge_dataframes
from utils import create_summary_report, save_json_report, create_directory_if_not_exists
import pandas as pd
import numpy as np
from datetime import datetime

In [23]:
# ƒê·ªçc d·ªØ li·ªáu nh√¢n vi√™n
data_path = os.path.join(os.path.dirname(os.getcwd()), 'data', 'employees.xlsx')
employees_df = read_excel_file(data_path)

print(f"ƒê√£ t·∫£i {len(employees_df)} b·∫£n ghi nh√¢n vi√™n")
print("\nTh√¥ng tin c·ªôt:")
print(employees_df.info())
print("\n5 d√≤ng ƒë·∫ßu:")
employees_df.head()

‚úÖ ƒê√£ ƒë·ªçc th√†nh c√¥ng file: employees.xlsx
üìä S·ªë d√≤ng: 20, S·ªë c·ªôt: 6
ƒê√£ t·∫£i 20 b·∫£n ghi nh√¢n vi√™n

Th√¥ng tin c·ªôt:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            20 non-null     int64
 1   H·ªç t√™n        20 non-null     object
 2   Ph√≤ng ban     20 non-null     object
 3   L∆∞∆°ng c∆° b·∫£n  20 non-null     int64
 4   Ng√†y v√†o l√†m  20 non-null     datetime64[ns]
 5   Tu·ªïi          20 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 1.1+ KB
None

5 d√≤ng ƒë·∫ßu:

   ID         H·ªç t√™n  Ph√≤ng ban  L∆∞∆°ng c∆° b·∫£n            Ng√†y v√†o l√†m  Tu·ªïi
0   1  Nguy·ªÖn VƒÉn An  Marketing      17784633 2020-01-01 00:00:00.000    23
1   2  Tr·∫ßn Th·ªã B√¨nh   B√°n h√†ng      13664789 2020-03-17 20:12:37.895    41
2   3   L√™ VƒÉn C∆∞·ªùng    Nh√¢n s·ª±      17695979 2020-06-02 16:25:15.789    49
3   4  Ph·∫°m Th·ªã Dung   B√°n h√†ng      17305648 2020-08-18 12:37:53.684    28
4   5   Ho√†ng VƒÉn Em   B√°n h√†ng      13743066 2020-11-03 08:50:31.579    29

In [24]:
# Ph√¢n t√≠ch d·ªØ li·ªáu
print("=== PH√ÇN T√çCH D·ªÆ LI·ªÜU NH√ÇN VI√äN ===")

# Th·ªëng k√™ theo ph√≤ng ban
dept_stats = employees_df.groupby('Ph√≤ng ban').agg({
    'ID': 'count',
    'L∆∞∆°ng c∆° b·∫£n': ['mean', 'min', 'max'],
    'Tu·ªïi': 'mean'
}).round(2)

# Flatten MultiIndex columns
dept_stats.columns = ['_'.join(col).strip() for col in dept_stats.columns]

print("\nTh·ªëng k√™ theo ph√≤ng ban:")
print(dept_stats)

# Th·ªëng k√™ l∆∞∆°ng
print(f"\nL∆∞∆°ng trung b√¨nh: {employees_df['L∆∞∆°ng c∆° b·∫£n'].mean():,.0f} VND")
print(f"L∆∞∆°ng cao nh·∫•t: {employees_df['L∆∞∆°ng c∆° b·∫£n'].max():,.0f} VND")
print(f"L∆∞∆°ng th·∫•p nh·∫•t: {employees_df['L∆∞∆°ng c∆° b·∫£n'].min():,.0f} VND")

# Ph√¢n b·ªë tu·ªïi
age_stats = employees_df['Tu·ªïi'].describe()
print(f"\nTh·ªëng k√™ tu·ªïi:")
print(age_stats)

=== PH√ÇN T√çCH D·ªÆ LI·ªÜU NH√ÇN VI√äN ===

Th·ªëng k√™ theo ph√≤ng ban:
           ID_count  L∆∞∆°ng c∆° b·∫£n_mean  L∆∞∆°ng c∆° b·∫£n_min  L∆∞∆°ng c∆° b·∫£n_max  \
Ph√≤ng ban
B√°n h√†ng          6        16570423.33          10663046          24861870
IT                1         9465689.00           9465689           9465689
K·∫ø to√°n           3        16328953.67          11385357          18959014
Marketing         5        20611462.00          13147581          24845364
Nh√¢n s·ª±           5        16824903.40          10428388          21237723

           Tu·ªïi_mean
Ph√≤ng ban
B√°n h√†ng       33.33
IT             29.00
K·∫ø to√°n        39.00
Marketing      33.20
Nh√¢n s·ª±        37.00

L∆∞∆°ng trung b√¨nh: 17,252,846 VND
L∆∞∆°ng cao nh·∫•t: 24,861,870 VND
L∆∞∆°ng th·∫•p nh·∫•t: 9,465,689 VND

Th·ªëng k√™ tu·ªïi:
count    20.000000
mean     34.850000
std       9.189668
min      23.000000
25%      27.750000
50%      35.000000
75%      39.500000
max      52.000000
Name: Tu·ªïi, dtype: float64

In [25]:
# T·∫°o b√°o c√°o t√≥m t·∫Øt
summary_data = {
    'report_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'total_employees': len(employees_df),
    'departments': employees_df['Ph√≤ng ban'].nunique(),
    'average_salary': round(employees_df['L∆∞∆°ng c∆° b·∫£n'].mean(), 2),
    'average_age': round(employees_df['Tu·ªïi'].mean(), 1),
    'salary_range': {
        'min': float(employees_df['L∆∞∆°ng c∆° b·∫£n'].min()),
        'max': float(employees_df['L∆∞∆°ng c∆° b·∫£n'].max())
    },
    'department_breakdown': employees_df['Ph√≤ng ban'].value_counts().to_dict(),
    'age_distribution': {
        'under_30': len(employees_df[employees_df['Tu·ªïi'] < 30]),
        'between_30_40': len(employees_df[(employees_df['Tu·ªïi'] >= 30) & (employees_df['Tu·ªïi'] < 40)]),
        'over_40': len(employees_df[employees_df['Tu·ªïi'] >= 40])
    }
}

print("B√°o c√°o t√≥m t·∫Øt:")
print(f"- T·ªïng s·ªë nh√¢n vi√™n: {summary_data['total_employees']}")
print(f"- S·ªë ph√≤ng ban: {summary_data['departments']}")
print(f"- L∆∞∆°ng trung b√¨nh: {summary_data['average_salary']:,.0f} VND")
print(f"- Tu·ªïi trung b√¨nh: {summary_data['average_age']} tu·ªïi")

B√°o c√°o t√≥m t·∫Øt:
- T·ªïng s·ªë nh√¢n vi√™n: 20
- S·ªë ph√≤ng ban: 5
- L∆∞∆°ng trung b√¨nh: 17,252,846 VND
- Tu·ªïi trung b√¨nh: 34.8 tu·ªïi

In [26]:
# L∆∞u k·∫øt qu·∫£ ra th∆∞ m·ª•c output
output_dir = os.path.join(os.path.dirname(os.getcwd()), 'output')

# 1. L∆∞u b√°o c√°o th·ªëng k√™ ph√≤ng ban th√†nh Excel
stats_file = os.path.join(output_dir, 'employee_department_stats.xlsx')
save_to_excel(dept_stats.reset_index(), stats_file)
print(f"‚úÖ ƒê√£ l∆∞u th·ªëng k√™ ph√≤ng ban: {stats_file}")

# 2. L∆∞u d·ªØ li·ªáu t√≥m t·∫Øt th√†nh JSON
json_file = os.path.join(output_dir, 'employee_summary.json')
save_json_report(summary_data, json_file)
print(f"‚úÖ ƒê√£ l∆∞u t√≥m t·∫Øt JSON: {json_file}")

# 3. L∆∞u b√°o c√°o vƒÉn b·∫£n
report_file = os.path.join(output_dir, 'employee_analysis_report.txt')
create_summary_report(summary_data, report_file)
print(f"‚úÖ ƒê√£ l∆∞u b√°o c√°o vƒÉn b·∫£n: {report_file}")

# 4. L∆∞u danh s√°ch nh√¢n vi√™n l∆∞∆°ng cao (top 20%)
high_salary_threshold = employees_df['L∆∞∆°ng c∆° b·∫£n'].quantile(0.8)
high_salary_df = employees_df[employees_df['L∆∞∆°ng c∆° b·∫£n'] > high_salary_threshold]
high_salary_file = os.path.join(output_dir, 'high_salary_employees.xlsx')
save_to_excel(high_salary_df, high_salary_file)
print(f"‚úÖ ƒê√£ l∆∞u danh s√°ch l∆∞∆°ng cao: {high_salary_file}")

# 5. L∆∞u nh√¢n vi√™n tr·∫ª (d∆∞·ªõi 30 tu·ªïi)
young_employees = employees_df[employees_df['Tu·ªïi'] < 30]
young_file = os.path.join(output_dir, 'young_employees.xlsx')
save_to_excel(young_employees, young_file)
print(f"‚úÖ ƒê√£ l∆∞u danh s√°ch nh√¢n vi√™n tr·∫ª: {young_file}")

print(f"\nüéâ Ho√†n th√†nh! ƒê√£ t·∫°o {5} file output t·ª´ ph√¢n t√≠ch d·ªØ li·ªáu nh√¢n vi√™n.")

üíæ ƒê√£ l∆∞u file Excel: d:\twan-projects\nbrunner\resources\output\employee_department_stats.xlsx
‚úÖ ƒê√£ l∆∞u th·ªëng k√™ ph√≤ng ban: d:\twan-projects\nbrunner\resources\output\employee_department_stats.xlsx
üíæ ƒê√£ l∆∞u JSON t·∫°i: d:\twan-projects\nbrunner\resources\output\employee_summary.json
‚úÖ ƒê√£ l∆∞u t√≥m t·∫Øt JSON: d:\twan-projects\nbrunner\resources\output\employee_summary.json
üìä ƒê√£ t·∫°o b√°o c√°o t·∫°i: d:\twan-projects\nbrunner\resources\output\employee_analysis_report.txt
‚úÖ ƒê√£ l∆∞u b√°o c√°o vƒÉn b·∫£n: d:\twan-projects\nbrunner\resources\output\employee_analysis_report.txt
üíæ ƒê√£ l∆∞u file Excel: d:\twan-projects\nbrunner\resources\output\high_salary_employees.xlsx
‚úÖ ƒê√£ l∆∞u danh s√°ch l∆∞∆°ng cao: d:\twan-projects\nbrunner\resources\output\high_salary_employees.xlsx
üíæ ƒê√£ l∆∞u file Excel: d:\twan-projects\nbrunner\resources\output\young_employees.xlsx
‚úÖ ƒê√£ l∆∞u danh s√°ch nh√¢n vi√™n tr·∫ª: d:\twan-projects\nbrunner\resources\output\young_employees.xlsx

üéâ Ho√†n th√†nh! ƒê√£ t·∫°o 5 file output t·ª´ ph√¢n t√≠ch d·ªØ li·ªáu nh√¢n vi√™n.